swagger: '2.0'
info:
  description: >-
    This web service provides a RESTful interface to Alma.
  version: 1.0.0
  title: Alma API
  contact:
    email: andy.goodnough@wisc.edu
schemes:
  - https
  - http
host: api-na.hosted.exlibrisgroup.com
basePath: /almaws/v1
tags:
  - name: users
    description: Users
paths:
  '/users/{user_id}':
    get:
      tags:
        - users
      summary: Get user details
      description: Returns a specific user's details
      operationId: getUserDetails
      produces:
        - application/json
        - application/xml
      parameters:
        - name: user_id
          in: path
          description: Id of user to retrieve
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/User'
        '404':
          description: Not found
          schema:
            $ref: '#/definitions/NotFound'
      security:
        - APIKeyHeader: []
        # - APIKeyQueryParam: []
securityDefinitions:
   # Authorization: apikey xxx
   APIKeyHeader:
     type: apiKey
     in: header
     name: Authorization
   # /path?apikey=xxx
   APIKeyQueryParam:
     type: apiKey
     in: query
     name: apikey
definitions:
  User:
    type: object
    properties:
      record_type:
        $ref: '#/definitions/RecordType'
      primary_id:
        type: string
        example: 6032840010780086
      first_name:
        type: string
        example: ANDY
      middle_name:
        type: string
        example: G
      last_name:
        type: string
        example: GOODNOUGH
      full_name:
        type: string
        example: ANDY G GOODNOUGH
      pin_number:
        type: string
        example: 1234
      user_title:
        $ref: '#/definitions/UserTitle'
      job_category:
        $ref: '#/definitions/JobCategory'
      job_description:
        type: string
        example:
      gender:
        $ref: '#/definitions/Gender'
      user_group:
        $ref: '#/definitions/UserGroup'
      campus_code:
        $ref: '#/definitions/CampusCode'
      web_site_url:
        type: string
        example:
      cataloger_level:
        $ref: '#/definitions/CatalogerLevel'
      preferred_language:
        $ref: '#/definitions/PreferredLanguage'
      account_type:
        $ref: '#/definitions/AccountType'
      external_id:
        type: string
        example: SIS
      password:
        type: string
        example:
      force_password_change:
        type: string
        example:
      status:
        $ref: '#/definitions/StatusCode'
      status_date:
        type: string
        example:
      requests:
        type: string
        example:
      loans:
        type: string
        example:
      fees:
        type: string
        example:
      contact_info:
        $ref: '#/definitions/ContactInfo'
      pref_first_name:
        type: string
        example:
      pref_middle_name:
        type: string
        example:
      pref_last_name:
        type: string
        example:
      researcher:
        type: string
        example:
      link:
        type: string
        example:
      user_identifier:
        type: array
        items:
          $ref: '#/definitions/UserIdentifier'
      user_role:
        type: array
        items:
          $ref: '#/definitions/UserRole'
      user_block:
        type: array
        items:
          $ref: '#/definitions/UserBlock'
      user_note:
        type: array
        items:
          $ref: '#/definitions/UserNote'
      user_statistic:
        type: array
        items:
          $ref: '#/definitions/UserStatistic'
      proxy_for_user:
        type: string
        example:
      rs_library:
        type: array
        items:
          $ref: '#/definitions/RsLibrary'
  RecordType:
    type: object
    properties:
      value:
        type: string
        example: PUBLIC
      desc:
        type: string
        example: Public
  UserTitle:
    type: object
    properties:
      value:
        type: string
        example:
      desc:
        type: string
        example:
  JobCategory:
    type: object
    properties:
      value:
        type: string
        example:
      desc:
        type: string
        example:
  Gender:
    type: object
    properties:
      value:
        type: string
        example:
      desc:
        type: string
        example:
  UserGroup:
    type: object
    properties:
      value:
        type: string
        example: STAFF
      desc:
        type: string
        example: STAFF
  CampusCode:
    type: object
    properties:
      value:
        type: string
        example:
      desc:
        type: string
        example:
  CatalogerLevel:
    type: object
    properties:
      value:
        type: string
        example: 00
      desc:
        type: string
        example: '[00] Default Level'
  PreferredLanguage:
    type: object
    properties:
      value:
        type: string
        example: en
      desc:
        type: string
        example: English
  AccountType:
    type: object
    properties:
      value:
        type: string
        example: INTERNAL
      desc:
        type: string
        example: Internal
  ContactInfo:
    type: object
    properties:
      address:
        type: array
        items:
          $ref: '#/definitions/Address'
      email:
        type: array
        items:
          $ref: '#/definitions/Email'
      phone:
        type: array
        items:
          $ref: '#/definitions/Phone'
  Address:
    type: object
    properties:
      line1:
        type: string
        example: 728 STATE ST
      line2:
        type: string
        example: 436 MEMORIAL LIBRARY
      line3:
        type: string
        example:
      line4:
        type: string
        example:
      line5:
        type: string
        example:
      city:
        type: string
        example: MADISON
      state_province:
        type: string
        example: WI
      postal_code:
        type: string
        example: 53706-1418
      country:
        $ref: '#/definitions/CountryCode'
      address_note:
        type: string
        example:
      start_date:
        type: string
        example: 2018-06-14Z
      preferred:
        type: boolean
        example: true
      segment_type:
        type: string
        example: Internal
      address_type:
        type: array
        items:
          $ref: '#/definitions/AddressTypeCode'
  Email:
    type: object
    properties:
      email_address:
        type: string
        example: andy.goodnough@wisc.edu
      description:
        type: string
        example: Home
      preferred:
        type: boolean
        example: true
      segment_type:
        type: string
      email_type:
        $ref: '#/definitions/EmailTypeCode'
  Phone:
    type: object
    properties:
      phone_number:
        type: string
        example: 608/262-7789
      preferred:
        type: boolean
        example: true
      preferred_sms:
        type: boolean
        example: false
      segment_type:
        type: string
      phone_type:
        $ref: '#/definitions/PhoneTypeCode'
  UserIdentifier:
    type: object
    properties:
      value:
        type: string
      id_type:
        $ref: '#/definitions/UserIdentifierIdTypeCode'
      note:
        type: string
      status:
        type: string
      segment_type:
        type: string
  UserRole:
    type: object
    properties:
      status:
        $ref: '#/definitions/UserRoleStatusCode'
      scope:
        $ref: '#/definitions/UserRoleScopeCode'
      role_type:
        $ref: '#/definitions/UserRoleRoleTypeCode'
      parameter:
        type: array
        items:
          $ref: '#/definitions/Parameter'
  UserBlock:
    type: object
    properties:
      block_type:
        $ref: '#/definitions/UserBlockCode'
      block_description:
        type: string
      block_status:
        type: string
      block_note:
        type: string
      created_by:
        type: string
      created_date:
        type: string
      expiry_date:
        type: string
      item_loan_id:
        type: string
  UserNote:
    type: object
    properties:
      note_type:
        $ref: '#/definitions/UserNoteCode'
      note_text:
        type: string
      user_viewable:
        type: boolean
      created_by:
        type: string
      created_date:
        type: string
      segment_type:
        type: string
  UserStatistic:
    type: object
    properties:
      statistic_category:
        $ref: '#/definitions/UserStatisticCode'
      segment_type:
        type: string
  RsLibrary:
    type: object
    properties:
      code:
        $ref: '#/definitions/RsLibraryCode'
  StatusCode:
    type: object
    properties:
      value:
        type: string
        example: ACTIVE
      desc:
        type: string
        example: Active
  ParameterTypeCode:
    type: object
    properties:
      value:
        type: string
        example: Read only
      desc:
        type: string
        example:
  ParameterValueCode:
    type: object
    properties:
      value:
        type: string
        example: "false"
      desc:
        type: string
        example: Active
  CountryCode:
    type: object
    properties:
      value:
        type: string
        example: USA
      desc:
        type: string
        example: United States
  AddressTypeCode:
    type: object
    properties:
      value:
        type: string
        example: work
      desc:
        type: string
        example: Work
  EmailTypeCode:
    type: object
    properties:
      value:
        type: string
        example: work
      desc:
        type: string
        example: Work
  PhoneTypeCode:
    type: object
    properties:
      value:
        type: string
        example: office
      desc:
        type: string
        example: Office
  UserIdentifierIdTypeCode:
    type: object
    properties:
      value:
        type: string
        example: BARCODE
      desc:
        type: string
        example: Barcode
  UserRoleStatusCode:
    type: object
    properties:
      value:
        type: string
        example: ACTIVE
      desc:
        type: string
        example: Active
  UserRoleScopeCode:
    type: object
    properties:
      value:
        type: string
        example: 01UWI_MAD
      desc:
        type: string
        example: University of Wisconsin - Madison
  UserRoleRoleTypeCode:
    type: object
    properties:
      value:
        type: string
        example: 200
      desc:
        type: string
        example: Patron
  UserBlockCode:
    type: object
    properties:
      value:
        type: string
        example:
      desc:
        type: string
        example:
  UserNoteCode:
    type: object
    properties:
      value:
        type: string
        example: OTHER
      desc:
        type: string
        example: Other
  UserStatisticCode:
    type: object
    properties:
      value:
        type: string
        example: PHARM/PHARMACY
      desc:
        type: string
        example:
  RsLibraryCode:
    type: object
    properties:
      value:
        type: string
        example: MEMORIAL
      desc:
        type: string
        example: Memorial Library
  Parameter:
    type: object
    properties:
      type:
        $ref: '#/definitions/ParameterTypeCode'
      value:
        $ref: '#/definitions/ParameterValueCode'
  NotFound:
    type: object
    properties:
      errorsExist:
        type: boolean
        example: true
      errorList:
        type: array
        items:
          $ref: '#/definitions/AlmaError'
  AlmaError:
    type: object
    properties:
      errorCode:
        type: string
        example: 401861
      errorMessage:
        type: string
        example: User with identifier 90801254700/dsd was not found
      trackingId:
        type: string
        example: E01-2510163523-NC9N4-AWAE653240618
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
